# Generated by Django 2.1 on 2018-08-12 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asm_id', models.IntegerField(help_text='Asmens id is used internally in seimas web', unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('is_male', models.BooleanField(default=True)),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('bio_url', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='politicians', to='seimas.Party')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.PositiveSmallIntegerField()),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('ses_id', models.IntegerField(help_text='Sesijos id is used internally in seimas web', unique=True)),
            ],
            options={
                'ordering': ['term', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('kad_id', models.IntegerField(help_text='Kadencijos id is used internally in seimas web', unique=True)),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.AddField(
            model_name='session',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='seimas.Term'),
        ),
        migrations.AddField(
            model_name='politician',
            name='sessions',
            field=models.ManyToManyField(related_name='politicians', to='seimas.Session'),
        ),
    ]
