# Generated by Django 2.1 on 2018-08-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seimas', '0002_auto_20180812_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='bio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
