# Generated by Django 2.1 on 2018-08-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seimas', '0003_auto_20180812_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Election types',
            },
        ),
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['-start'], 'verbose_name_plural': 'Terms'},
        ),
        migrations.RenameField(
            model_name='politician',
            old_name='party',
            new_name='elected_party',
        ),
        migrations.RemoveField(
            model_name='politician',
            name='terms',
        ),
    ]
