# Generated by Django 2.1 on 2018-08-13 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seimas', '0004_auto_20180813_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticianParliamentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=128)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('group_id', models.IntegerField(help_text='parlamentinės_grupės_id is used internally in seimas web', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Politician parliament groups',
                'ordering': ['politician', 'start'],
            },
        ),
        migrations.AddField(
            model_name='politician',
            name='personal_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politicianparliamentgroup',
            name='politician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seimas.Politician'),
        ),
        migrations.AlterUniqueTogether(
            name='politicianparliamentgroup',
            unique_together={('politician', 'name', 'role')},
        ),
    ]
