# Generated by Django 2.1 on 2018-08-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seimas', '0005_auto_20180813_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicianparliamentgroup',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='politicianparliamentgroup',
            unique_together={('politician', 'group_id', 'role')},
        ),
    ]
