# Generated by Django 2.1 on 2018-08-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seimas', '0006_auto_20180813_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicianparliamentgroup',
            name='group_id',
            field=models.IntegerField(help_text='parlamentinės_grupės_id is used internally in seimas web'),
        ),
    ]
