# Generated by Django 2.1 on 2018-08-13 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seimas', '0007_auto_20180813_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticianDivisions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=128)),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('pad_id', models.IntegerField(help_text='padalinio_id is used internally in seimas web')),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='seimas.Politician')),
            ],
            options={
                'verbose_name_plural': 'Politician divisions',
                'ordering': ['politician', 'start'],
            },
        ),
        migrations.AlterField(
            model_name='politicianparliamentgroup',
            name='politician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parliament_groups', to='seimas.Politician'),
        ),
        migrations.AlterUniqueTogether(
            name='politiciandivisions',
            unique_together={('politician', 'pad_id', 'role')},
        ),
    ]
