# Generated by Django 2.1 on 2018-08-13 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seimas', '0008_auto_20180813_1333'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PoliticianDivisions',
            new_name='PoliticianDivision',
        ),
    ]
