# Generated by Django 2.1 on 2018-08-13 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seimas', '0009_auto_20180813_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticianBusinessTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('is_secondment', models.BooleanField(default=False, verbose_name='True stands for Kelionė, False for Komandiruotė')),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_trips', to='seimas.Politician')),
            ],
            options={
                'verbose_name_plural': 'Politician business trips',
                'ordering': ['politician', '-start'],
            },
        ),
        migrations.AlterModelOptions(
            name='politicianparliamentgroup',
            options={'ordering': ['politician', '-start'], 'verbose_name_plural': 'Politician parliament groups'},
        ),
        migrations.AlterUniqueTogether(
            name='politicianbusinesstrip',
            unique_together={('politician', 'name')},
        ),
    ]
