# Generated by Django 2.1 on 2018-08-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seimas', '0011_auto_20180813_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
