# Generated by Django 2.1 on 2018-08-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seimas', '0012_auto_20180816_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicianbusinesstrip',
            name='is_secondment',
            field=models.BooleanField(default=False, help_text='True stands for Komandiruotė, False for Kelionė'),
        ),
    ]
