# Generated by Django 2.1 on 2018-08-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seimas', '0013_auto_20180816_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
