# Generated by Django 2.1 on 2018-08-16 08:49

from django.db import migrations, models
import seimas.models


class Migration(migrations.Migration):

    dependencies = [
        ('seimas', '0014_politician_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=seimas.models.Politician._politician_photo_file),
        ),
    ]
