# Generated by Django 2.1 on 2018-08-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seimas', '0017_term_politicians'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='politicians',
            field=models.ManyToManyField(blank=True, related_name='terms', to='seimas.Politician'),
        ),
    ]
