# Generated by Django 2.1 on 2018-08-16 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seimas', '0018_auto_20180816_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticianTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('elected_by_list', models.BooleanField(default=True)),
                ('elected_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='politician_terms', to='seimas.Party')),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='politician_terms', to='seimas.Politician')),
            ],
            options={
                'verbose_name_plural': 'Politician terms',
                'ordering': ['politician', 'term'],
            },
        ),
        migrations.RemoveField(
            model_name='term',
            name='politicians',
        ),
        migrations.AddField(
            model_name='politicianterm',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='politician_terms', to='seimas.Term'),
        ),
        migrations.AlterUniqueTogether(
            name='politicianterm',
            unique_together={('politician', 'term')},
        ),
    ]
