# Generated by Django 2.1 on 2018-08-16 18:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seimas', '0020_auto_20180816_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticianGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ended', models.DateTimeField(blank=True, null=True)),
                ('user_ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answered_politicians', models.ManyToManyField(blank=True, to='seimas.Politician')),
                ('correct_politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='seimas.Politician')),
                ('first_politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='seimas.Politician')),
                ('lost_on_politician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_lost_politicians', to='seimas.Politician')),
                ('second_politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='seimas.Politician')),
            ],
        ),
    ]
