# Generated by Django 2.1 on 2018-08-16 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seimas', '0021_politiciangame'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='politiciangame',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Politicians game'},
        ),
    ]
