# Generated by Django 2.1 on 2018-09-05 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seimas', '0023_politiciangame_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Legal acts',
            },
        ),
        migrations.CreateModel(
            name='LegalActDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=1024)),
                ('date', models.DateField(db_index=True)),
            ],
            options={
                'verbose_name_plural': 'Legal act documents',
                'ordering': ['date', 'doc_id'],
            },
        ),
        migrations.CreateModel(
            name='LegalActDocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Legal act document types',
            },
        ),
        migrations.AddField(
            model_name='legalactdocument',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='seimas.LegalActDocumentType'),
        ),
        migrations.AddField(
            model_name='legalactdocument',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='seimas.LegalAct'),
        ),
        migrations.AddField(
            model_name='politician',
            name='legal_act_documents',
            field=models.ManyToManyField(related_name='politicians', to='seimas.LegalActDocument'),
        ),
    ]
