# Generated by Django 2.1 on 2018-09-05 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seimas', '0024_auto_20180905_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legalactdocument',
            old_name='project',
            new_name='legal_act',
        ),
    ]
