# Generated by Django 2.1 on 2018-09-05 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seimas', '0025_auto_20180905_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalactdocument',
            options={'ordering': ['-date', '-doc_id'], 'verbose_name_plural': 'Legal act documents'},
        ),
    ]
