# Generated by Django 2.1.1 on 2018-10-18 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seimas', '0026_auto_20180905_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('short_name', models.CharField(max_length=32)),
                ('seimas_pad_id', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Fractions',
                'ordering': ['seimas_pad_id'],
            },
        ),
        migrations.CreateModel(
            name='PoliticianFraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=128)),
                ('fraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='politicians', to='seimas.Fraction')),
                ('politician', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='politician_fraction', to='seimas.Politician')),
            ],
            options={
                'verbose_name_plural': 'Politician fractions',
            },
        ),
    ]
