# Generated by Django 2.1.1 on 2019-01-03 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seimas', '0027_fraction_politicianfraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('is_main_committee', models.BooleanField(default=True)),
                ('seimas_pad_id', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Komitetai',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PoliticianCommittee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=128)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='politicians', to='seimas.Committee')),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='politician_committees', to='seimas.Politician')),
            ],
            options={
                'verbose_name_plural': 'Politikų komitetai',
            },
        ),
    ]
