# Generated by Django 2.1.1 on 2019-01-03 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seimas', '0028_committee_politiciancommittee'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='politiciancommittee',
            unique_together={('committee', 'politician')},
        ),
    ]
