# Generated by Django 2.1.1 on 2019-01-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seimas', '0029_auto_20190103_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fraction',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
