# Generated by Django 2.1.4 on 2019-01-03 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seimas', '0030_auto_20190103_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='fraction',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
