# Generated by Django 2.1.4 on 2019-01-04 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seimas', '0032_auto_20190103_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(unique=True)),
                ('seimas_pad_id', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Komsija',
                'verbose_name_plural': 'Komisijos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PoliticianCommission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=128)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='politicians', to='seimas.Commission')),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='politician_commissions', to='seimas.Politician')),
            ],
            options={
                'verbose_name': 'Politikų komisija',
                'verbose_name_plural': 'Politikų komisijos',
            },
        ),
        migrations.AlterModelOptions(
            name='committee',
            options={'ordering': ['name'], 'verbose_name': 'Komitetas', 'verbose_name_plural': 'Komitetai'},
        ),
        migrations.AlterModelOptions(
            name='fraction',
            options={'ordering': ['name'], 'verbose_name': 'Frakcija', 'verbose_name_plural': 'Frakcijos'},
        ),
        migrations.AlterUniqueTogether(
            name='politiciancommission',
            unique_together={('commission', 'politician')},
        ),
    ]
