# Generated by Django 2.1.4 on 2019-01-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seimas', '0033_auto_20190104_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='slug',
            field=models.SlugField(max_length=128, unique=True),
        ),
    ]
