# Generated by Django 2.1.1 on 2018-10-11 07:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0002_auto_20181010_2206'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='PoliticianAnswer',
        ),
    ]
