# Generated by Django 2.1.1 on 2018-10-11 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20181011_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politiciananswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='politian_answer', to='questions.Question'),
        ),
    ]
