# Generated by Django 2.1.1 on 2018-11-05 12:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import questions.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20181018_0007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='politiciananswer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Politiko atsakymas', 'verbose_name_plural': 'Politikų atsakymai'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at'], 'verbose_name': 'Klausimas politikui', 'verbose_name_plural': 'Klausimai politikams'},
        ),
        migrations.AlterField(
            model_name='politiciananswer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_answers', to=settings.AUTH_USER_MODEL, verbose_name='Atsakymo autorius'),
        ),
        migrations.AlterField(
            model_name='politiciananswer',
            name='text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Politiko atsakymas'),
        ),
        migrations.AlterField(
            model_name='politiciananswer',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='Atsakymo autoriaus user-agent'),
        ),
        migrations.AlterField(
            model_name='politiciananswer',
            name='user_country',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Atsakymo autoriaus user-country'),
        ),
        migrations.AlterField(
            model_name='politiciananswer',
            name='user_ip',
            field=models.GenericIPAddressField(verbose_name='Atsakymo autoriaus IP'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Klausimas sukūrimo data'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='Klausimo autorius'),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='Klausimo pavadinimas'),
        ),
        migrations.AlterField(
            model_name='question',
            name='politician',
            field=models.ForeignKey(help_text='Nurodo politiką, kuriam skirtas klausimas', on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='web.PoliticianInfo', verbose_name='Politikas'),
        ),
        migrations.AlterField(
            model_name='question',
            name='rejected_reason',
            field=models.TextField(blank=True, help_text='Būtina užpildyti jei klausimas yra atmetamas', null=True, verbose_name='Klausimo atmetimo priežastis'),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=enumfields.fields.EnumIntegerField(db_index=True, default=1, enum=questions.models.QuestionStatus, verbose_name='Klausimo būsena'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Klausimo tekstas'),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Klausimo atnaujinimo data'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='Klausimo autoriaus User-agent'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user_country',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Klausimo autoriaus šalis'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user_ip',
            field=models.GenericIPAddressField(verbose_name='Klausimo autoriaus IP'),
        ),
    ]
