# Generated by Django 2.1.1 on 2018-11-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20181105_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politiciananswer',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='Atsakymo autoriaus User-agent'),
        ),
        migrations.AlterField(
            model_name='politiciananswer',
            name='user_country',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Atsakymo autoriaus šalis'),
        ),
    ]
