# Generated by Django 2.1.1 on 2018-12-10 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20181105_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(15), django.core.validators.MaxLengthValidator(500)], verbose_name='Klausimo tekstas'),
        ),
    ]
