# Generated by Django 2.1.1 on 2018-12-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20181210_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='politiciananswer',
            name='is_question_answered_letter_sent',
            field=models.BooleanField(default=False, verbose_name='Ar laiškas apie atsakytą klausimą buvo išsiųstas'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_letter_for_politician_sent',
            field=models.BooleanField(default=False, verbose_name='Ar laiškas politikui apoe jam užduotą klausimą buvo išsiųstas'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_moderator_decision_letter_sent',
            field=models.BooleanField(default=False, verbose_name='Ar išsiųstas laiškas apie klausimo patvirtnimą / atmetimą'),
        ),
    ]
