# Generated by Django 2.1.1 on 2018-12-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_auto_20181213_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politiciananswer',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Atsakymo autoriaus IP'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Klausimo autoriaus IP'),
        ),
    ]
