# Generated by Django 2.1.1 on 2018-12-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_auto_20181213_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_letter_for_politician_sent',
            field=models.BooleanField(default=False, verbose_name='Ar laiškas politikui apie jam užduotą klausimą buvo išsiųstas'),
        ),
    ]
