# Generated by Django 2.1.5 on 2019-02-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_auto_20181214_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politiciananswer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Klausimas sukūrimo data'),
        ),
    ]
