language: generic

addons:
  sshknownhosts:
  - 178.128.199.74

before_install:
- set -e
- openssl aes-256-cbc -K $encrypted_c3e3f6321cf7_key -iv $encrypted_c3e3f6321cf7_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- set +e

after_success:
- set -e
- ssh -o "StrictHostKeyChecking no" -i /tmp/deploy_rsa -t $REMOTE_USER@$REMOTE_HOST << EOF
  set -e
  cd $REMOTEAPPDIR
  make
  set +e
  EOF
- set +e