language: generic

addons:
  sshknownhosts:
  - 178.128.199.74

before_deploy:
- openssl aes-256-cbc -K $encrypted_c3e3f6321cf7_key -iv $encrypted_c3e3f6321cf7_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

after_success:
- ssh $REMOTE_USER@$REMOTE_HOST
- cd $REMOTEAPPDIR
- make