language: generic

addons:
  sshknownhosts:
  - 178.128.199.74

before_install:
- openssl aes-256-cbc -K $encrypted_c3e3f6321cf7_key -iv $encrypted_c3e3f6321cf7_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

after_success:
- ssh -o "StrictHostKeyChecking no" -i /tmp/deploy_rsa $REMOTE_USER@$REMOTE_HOST
- cd $REMOTEAPPDIR
- make