version: "3"

services:

  platform:
    image: vycius/zkr-platform
    env_file:
    - .env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health/ || exit 1"]
    deploy:
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 15s
    volumes:
    - static_volume:/srv/platform/static
    - media_volume:/srv/platform/media
    networks:
    - nginx_network
    - database_network
    - redis_network
    depends_on:
    - postgres
    - redis

  nginx:
    image: nginx
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./config/nginx:/etc/nginx/conf.d
    - static_volume:/srv/platform/static
    - media_volume:/srv/platform/media
    depends_on:
    - platform
    networks:
    - nginx_network
    deploy:
      restart_policy:
        condition: on-failure

  postgres:
    image: postgres:10.5
    env_file:
    - .env
    networks:
    - database_network
    volumes:
    - database_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
    deploy:
      restart_policy:
        condition: on-failure

  redis:
    image: redis:4.0.11
    networks:
    - redis_network
    volumes:
    - redis_volume:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
    deploy:
      restart_policy:
        condition: on-failure

  celery_zkr_beat:
    image: vycius/zkr-platform
    env_file:
    - .env
    volumes:
    - static_volume:/srv/platform/static
    - media_volume:/srv/platform/media
    - worker_cache_volume:/srv/platform/worker_cache
    command: celery -A zkr beat -l info  --schedule=/srv/platform/celerybeat-schedule
    networks:
    - database_network
    - redis_network
    depends_on:
    - platform
    - postgres
    - redis
    deploy:
      restart_policy:
        condition: on-failure

  celery_zkr_default_worker:
    image: vycius/zkr-platform
    env_file:
    - .env
    volumes:
    - static_volume:/srv/platform/static
    - media_volume:/srv/platform/media
    - worker_cache_volume:/srv/platform/worker_cache
    command: celery -A zkr worker -l info -E --concurrency=3
    networks:
    - database_network
    - redis_network
    depends_on:
    - platform
    - postgres
    - redis
    deploy:
      restart_policy:
        condition: on-failure

networks:
  nginx_network:
    driver: overlay
  database_network:
    driver: overlay
  redis_network:
    driver: overlay

volumes:
  database_volume:
  static_volume:
  media_volume:
  redis_volume:
  worker_cache_volume:
