version: "3"

services:

  platform:
    container_name: zkr-platform
    build: .
    env_file:
    - .env
    healthcheck:
      test: ["CMD", "curl --fail http://localhost:8080/ || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
    - static_volume:/srv/platform/static
    - media_volume:/srv/platform/media
    networks:
    - nginx_network
    - database_network
    - redis_network
    depends_on:
    - postgres
    - redis

  nginx:
    container_name: zkr-nginx
    image: nginx
    ports:
    - 80:80
    volumes:
    - ./config/nginx:/etc/nginx/conf.d
    - static_volume:/srv/platform/static
    - media_volume:/srv/platform/media
    depends_on:
    - platform
    networks:
    - nginx_network

  postgres:
    container_name: zkr-postgres
    image: postgres
    env_file:
    - .env
    networks:
    - database_network
    volumes:
    - database_volume:/var/lib/postgresql/data

  redis:
    container_name: zkr-redis
    image: redis
    networks:
    - redis_network
    volumes:
    - redis_volume:/data

  celery_zkr_beat:
    container_name: celery-zkr-beat
    build: .
    env_file:
    - .env
    volumes:
    - static_volume:/srv/platform/static
    - media_volume:/srv/platform/media
    - /srv/platform/worker_cache:/srv/platform/worker_cache
    command: celery -A zkr beat -l info  --schedule=/srv/platform/celerybeat-schedule
    networks:
    - database_network
    - redis_network
    depends_on:
    - postgres
    - redis

  celery_zkr_default_worker:
    container_name: celery-zkr-default-worker
    build: .
    env_file:
    - .env
    volumes:
    - static_volume:/srv/platform/static
    - media_volume:/srv/platform/media
    - /srv/platform/worker_cache:/srv/platform/worker_cache
    command: celery -A zkr worker -l info -E --concurrency=3
    networks:
    - database_network
    - redis_network
    depends_on:
    - celery_zkr_beat

  zkr_flower:
    container_name: zkr-flower
    image: mher/flower
    env_file:
    - .env
    environment:
    - CELERY_BROKER_URL=redis://redis:6379/0
    command: flower flower --port=5555
    ports:
    - 5555:5555
    networks:
    - redis_network
    depends_on:
    - redis

networks:
  nginx_network:
    driver: bridge
  database_network:
    driver: bridge
  redis_network:
    driver: bridge

volumes:
  database_volume:
  static_volume:
  media_volume:
  redis_volume:
