# Generated by Django 2.1.1 on 2018-09-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('election_date', models.DateTimeField()),
                ('vrt_id', models.PositiveIntegerField()),
                ('vr_id', models.PositiveIntegerField()),
                ('rt_no', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Elections',
            },
        ),
    ]
