# Generated by Django 2.1.1 on 2018-09-28 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='election',
            options={'ordering': ['-election_date'], 'verbose_name_plural': 'Elections'},
        ),
    ]
