# Generated by Django 2.1.1 on 2018-09-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_auto_20180928_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='election',
            name='last_results_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
