# Generated by Django 2.1.1 on 2018-09-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_auto_20180929_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
