# Generated by Django 2.1.1 on 2018-09-29 08:00

from django.db import migrations, models
import django.db.models.deletion
import elections.models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_auto_20180929_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('party', models.CharField(blank=True, max_length=256, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=elections.models.ElectionResult._candidate_photo_file)),
                ('candidate_id', models.PositiveIntegerField(unique=True)),
                ('postal_votes', models.PositiveIntegerField()),
                ('ballot_votes', models.PositiveIntegerField()),
                ('percent_ballot_paper', models.PositiveIntegerField()),
                ('percent_voters', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='elections.Election')),
            ],
            options={
                'verbose_name_plural': 'Election results',
                'ordering': ['-percent_ballot_paper'],
            },
        ),
    ]
