# Generated by Django 2.1.1 on 2018-09-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_auto_20180929_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionresult',
            name='candidate_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='electionresult',
            unique_together={('election', 'candidate_id')},
        ),
    ]
