# Generated by Django 2.1.1 on 2018-12-07 13:25

from django.db import migrations, models
import django.db.models.deletion
import elections.models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0008_auto_20180930_0628'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresidentCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Kandidato vardas')),
                ('slug', models.SlugField(unique=True)),
                ('party', models.CharField(blank=True, max_length=256, verbose_name='Kandidato partija')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=elections.models.PresidentCandidate._candidate_photo_file, verbose_name='Kandidato nuotrauka')),
                ('candidate_program', models.URLField(blank=True, verbose_name='Kandidato rinkimė programa')),
                ('facebook', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atnaujinta')),
            ],
            options={
                'verbose_name': 'Kandidatas į prezidentus',
                'verbose_name_plural': 'Kandidatai į prezidentus',
            },
        ),
        migrations.CreateModel(
            name='PresidentCandidateArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.PresidentCandidate')),
            ],
            options={
                'verbose_name': 'Naujiena apie kandidatą į prezidentus',
                'verbose_name_plural': 'Naujienos apie kandidatus į prezidentus',
            },
        ),
        migrations.AlterUniqueTogether(
            name='presidentcandidatearticle',
            unique_together={('candidate', 'url')},
        ),
    ]
