# Generated by Django 2.1.1 on 2018-12-07 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0009_auto_20181207_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presidentcandidatearticle',
            options={'ordering': ['-created_at'], 'verbose_name': 'Naujiena apie kandidatą į prezidentus', 'verbose_name_plural': 'Naujienos apie kandidatus į prezidentus'},
        ),
    ]
