# Generated by Django 2.1.1 on 2018-12-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0010_auto_20181207_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presidentcandidate',
            name='party',
        ),
        migrations.AlterField(
            model_name='presidentcandidatearticle',
            name='url',
            field=models.URLField(verbose_name='Naujienos nuoroda'),
        ),
    ]
