# Generated by Django 2.1.1 on 2018-12-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0012_auto_20181207_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='presidentcandidate',
            name='short_description',
            field=models.CharField(blank=True, max_length=280, verbose_name='Trumpas aprašymas'),
        ),
    ]
