# Generated by Django 2.1.1 on 2018-12-08 16:04

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import elections.models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0013_presidentcandidate_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresidentCandidateArticleInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=256, verbose_name='Pavadinimas')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=False, null=True, quality=90, size=[256, 256], upload_to=elections.models.PresidentCandidateArticleInformation._article_photo_file, verbose_name='Nuotrauka')),
                ('description', models.TextField(verbose_name='Aprašymas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='information', to='elections.PresidentCandidateArticle', verbose_name='Naujiena')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
