# Generated by Django 2.1.1 on 2018-12-08 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0014_presidentcandidatearticleinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presidentcandidatearticle',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='elections.PresidentCandidate'),
        ),
    ]
