# Generated by Django 2.1.4 on 2019-01-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0017_auto_20181208_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='presidentcandidate',
            name='instagram',
            field=models.URLField(blank=True),
        ),
    ]
