# Generated by Django 2.1.5 on 2019-01-29 18:47

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import elections.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_auto_20190115_1046'),
        ('elections', '0018_presidentcandidate_instagram'),
    ]

    operations = [
        migrations.CreateModel(
            name='MayorCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256, verbose_name='Kandidato vardas')),
                ('last_name', models.CharField(max_length=256, verbose_name='Kandidato pavardė')),
                ('slug', models.SlugField(unique=True)),
                ('photo', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=False, null=True, quality=90, size=[256, 256], upload_to=elections.models.MayorCandidate._candidate_photo_file, verbose_name='Kandidato nuotrauka')),
                ('party', models.CharField(max_length=256, verbose_name='Iškėlusi partija arba rinkiminis komitetas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atnaujinta')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Municipality')),
            ],
            options={
                'verbose_name': 'Kandidatas į savivaldybės merus',
                'verbose_name_plural': 'Kandidatai į savivaldyvės merus',
            },
        ),
    ]
