# Generated by Django 2.1.5 on 2019-02-01 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0020_auto_20190129_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mayorcandidate',
            options={'verbose_name': 'Kandidatas į savivaldybės merus', 'verbose_name_plural': 'Kandidatai į savivaldybės merus'},
        ),
    ]
