# Generated by Django 2.1.4 on 2019-02-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0025_debates_municipality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debates',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Debatai'},
        ),
        migrations.AlterModelOptions(
            name='moderators',
            options={'ordering': ['last_name'], 'verbose_name': 'Moderatorius', 'verbose_name_plural': 'Moderatoriai'},
        ),
        migrations.AddField(
            model_name='debates',
            name='debate_youtube_video_url',
            field=models.URLField(blank=True, verbose_name='Debatų YouTube video url'),
        ),
    ]
