# Generated by Django 2.1.4 on 2019-02-03 00:36

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0026_auto_20190203_0015'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='debates',
            managers=[
                ('is_active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='debates',
            old_name='debate_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='debates',
            old_name='debate_facebook_url',
            new_name='facebook_url',
        ),
        migrations.RenameField(
            model_name='debates',
            old_name='debate_lat',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='debates',
            old_name='debate_lng',
            new_name='lng',
        ),
        migrations.RenameField(
            model_name='debates',
            old_name='debate_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='debates',
            old_name='debate_moderator',
            new_name='moderator',
        ),
        migrations.RenameField(
            model_name='debates',
            old_name='debate_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='debates',
            old_name='debate_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='debates',
            old_name='debate_youtube_video_url',
            new_name='youtube_video_url',
        ),
    ]
