# Generated by Django 2.1.4 on 2019-02-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0027_auto_20190203_0036'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='debates',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='debates',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
