# Generated by Django 2.1.4 on 2019-02-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0028_auto_20190203_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debates',
            name='lat',
            field=models.DecimalField(decimal_places=6, help_text='Google žemėlapiams', max_digits=8, verbose_name='Platuma'),
        ),
        migrations.AlterField(
            model_name='debates',
            name='lng',
            field=models.DecimalField(decimal_places=6, help_text='Google žemėlapiams', max_digits=8, verbose_name='Ilguma'),
        ),
        migrations.AlterField(
            model_name='debates',
            name='location',
            field=models.CharField(help_text='pvz: M. Mažvydo biblioteka', max_length=256, verbose_name='Debatų vieta'),
        ),
    ]
