# Generated by Django 2.1.4 on 2019-02-03 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0029_auto_20190203_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='debates',
            name='slug',
            field=models.SlugField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderators',
            name='slug',
            field=models.SlugField(default='moderator-test-slug', unique=True),
            preserve_default=False,
        ),
    ]
