# Generated by Django 2.1.4 on 2019-02-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0030_auto_20190203_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debates',
            name='lat',
            field=models.DecimalField(decimal_places=7, help_text='Google žemėlapiams', max_digits=10, verbose_name='Platuma'),
        ),
        migrations.AlterField(
            model_name='debates',
            name='lng',
            field=models.DecimalField(decimal_places=7, help_text='Google žemėlapiams', max_digits=10, verbose_name='Ilguma'),
        ),
    ]
