# Generated by Django 2.1.5 on 2019-02-12 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0031_auto_20190203_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='mayorcandidate',
            name='email',
            field=models.CharField(blank=True, max_length=256, verbose_name='Kandidato el. paštas'),
        ),
    ]
