# Generated by Django 2.1.5 on 2019-02-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0032_mayorcandidate_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mayorcandidate',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Kandidato el. paštas'),
        ),
    ]
