# Generated by Django 2.1.5 on 2019-03-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0033_auto_20190212_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='mayorcandidate',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Indikuoja ar kandidatas į merus aktyvus.', verbose_name='Aktyvus'),
        ),
    ]
