# Generated by Django 2.1.5 on 2019-03-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0034_mayorcandidate_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mayorcandidate',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Indikuoja ar kandidatas į merus matomas merų sąraše bei galima užduoti naują klausimą.', verbose_name='Aktyvus'),
        ),
    ]
