# Generated by Django 2.1.7 on 2019-03-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0035_auto_20190301_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='debates',
            name='tour_id',
            field=models.IntegerField(default=1, verbose_name='Turo numeris'),
        ),
    ]
