# Generated by Django 2.1.5 on 2019-03-07 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0036_debates_tour_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debates',
            options={'ordering': ['-created_at'], 'verbose_name': 'Debatai', 'verbose_name_plural': 'Debatai'},
        ),
        migrations.AlterField(
            model_name='debates',
            name='moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Moderators', verbose_name='Moderatorius'),
        ),
    ]
