# Generated by Django 2.1.5 on 2019-03-07 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0037_auto_20190307_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debates',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Aktyvus'),
        ),
        migrations.AlterField(
            model_name='debates',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Municipality', verbose_name='Savivaldybė'),
        ),
    ]
