# Generated by Django 2.1.7 on 2019-03-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0040_auto_20190331_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debates',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Google žemėlapiams', max_digits=10, null=True, verbose_name='Platuma'),
        ),
        migrations.AlterField(
            model_name='debates',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Google žemėlapiams', max_digits=10, null=True, verbose_name='Ilguma'),
        ),
    ]
