# Generated by Django 2.1.7 on 2019-03-31 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0044_auto_20190331_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debates',
            name='election_type',
            field=models.IntegerField(choices=[(1, 'Merų rinkimai'), (2, 'Seimo rinkimai'), (3, 'Europos Parlamento rinkimai'), (4, 'Prezidento rinkimai'), (5, 'Savivaldos tarybų rinkimai')], verbose_name='Rinkimų tipas'),
        ),
    ]
