# Generated by Django 2.1.7 on 2019-04-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0045_auto_20190331_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presidentcandidate',
            old_name='candidate_program',
            new_name='candidate_program_link',
        ),
        migrations.RemoveField(
            model_name='presidentcandidate',
            name='short_description',
        ),
        migrations.AddField(
            model_name='presidentcandidate',
            name='candidate_program_summary',
            field=models.TextField(blank=True, verbose_name='Kandidato programos santrauka'),
        ),
        migrations.AddField(
            model_name='presidentcandidate',
            name='candidate_program_title',
            field=models.CharField(blank=True, max_length=280, verbose_name='Kandidato programos pavadinimas'),
        ),
        migrations.AddField(
            model_name='presidentcandidate',
            name='party',
            field=models.CharField(blank=True, help_text='Jeigu kandidatas - be partijos, nurodykite, kad nepriklausomas', max_length=280, verbose_name='Partija'),
        ),
    ]
