# Generated by Django 2.1.7 on 2019-04-14 22:38

from django.db import migrations, models
import django_resized.forms
import elections.models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0046_auto_20190412_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='EuroParliamentCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indikuoja ar kandidatas į Europos Parlamentą matomas kandidatų sąraše bei galima užduoti naują klausimą.', verbose_name='Aktyvus')),
                ('first_name', models.CharField(max_length=256, verbose_name='Kandidato vardas')),
                ('last_name', models.CharField(max_length=256, verbose_name='Kandidato pavardė')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Kandidato el. paštas')),
                ('slug', models.SlugField(unique=True)),
                ('photo', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=False, null=True, quality=90, size=[256, 256], upload_to=elections.models.EuroParliamentCandidate._candidate_photo_file, verbose_name='Kandidato nuotrauka')),
                ('party', models.CharField(blank=True, max_length=256, verbose_name='Iškėlusi partija arba rinkiminis komitetas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atnaujinta')),
            ],
            options={
                'verbose_name': 'Kandidatas į Europos parlamentą',
                'verbose_name_plural': 'Kandidatai į Europos parlamentą',
            },
        ),
    ]
