# Generated by Django 2.1.7 on 2019-05-07 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0047_europarliamentcandidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresidentCandidateBiography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio_period', models.CharField(blank=True, max_length=15, verbose_name='Periodas')),
                ('bio_text', models.TextField(blank=True, verbose_name='Biografijos įrašas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biographies', to='elections.PresidentCandidate')),
            ],
            options={
                'verbose_name': 'Biografijos įrašas',
                'verbose_name_plural': 'Biografijos įrašai',
                'ordering': ['-created_at'],
            },
        ),
    ]
