# Generated by Django 2.1.7 on 2019-05-10 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0048_presidentcandidatebiography'),
    ]

    operations = [
        migrations.CreateModel(
            name='EuroParliamentCandidateBiography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio_period', models.CharField(blank=True, max_length=15, verbose_name='Periodas')),
                ('bio_text', models.TextField(blank=True, verbose_name='Biografijos įrašas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atnaujinta')),
            ],
            options={
                'verbose_name': 'Biografijos įrašas',
                'verbose_name_plural': 'Biografijos įrašai',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EuroParliamentCandidatePoliticalExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Pareigos')),
                ('office', models.CharField(blank=True, max_length=100, verbose_name='Institucija')),
                ('start', models.DateField(blank=True, verbose_name='Pereigų pradžia')),
                ('end', models.DateField(blank=True, verbose_name='Pereigų pabaiga')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atnaujinta')),
            ],
            options={
                'verbose_name': 'Politinė patirties įrašas',
                'verbose_name_plural': 'Politinės patirties įrašai',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EuroParliamentCandidateWorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Pareigos')),
                ('office', models.CharField(blank=True, max_length=100, verbose_name='Darbovietė')),
                ('start', models.DateField(blank=True, verbose_name='Pereigų pradžia')),
                ('end', models.DateField(blank=True, verbose_name='Pereigų pabaiga')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atnaujinta')),
            ],
            options={
                'verbose_name': 'Darbo patirties įrašas',
                'verbose_name_plural': 'Darbo patirties įrašai',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PresidentCandidatePoliticalExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Pareigos')),
                ('office', models.CharField(blank=True, max_length=100, verbose_name='Institucija')),
                ('start', models.DateField(blank=True, null=True, verbose_name='Pereigų pradžia')),
                ('end', models.DateField(blank=True, null=True, verbose_name='Pereigų pabaiga')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atnaujinta')),
            ],
            options={
                'verbose_name': 'Politinė patirties įrašas',
                'verbose_name_plural': 'Politinės patirties įrašai',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PresidentCandidateWorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Pareigos')),
                ('office', models.CharField(blank=True, max_length=100, verbose_name='Darbovietė')),
                ('start', models.DateField(blank=True, null=True, verbose_name='Pereigų pradžia')),
                ('end', models.DateField(blank=True, null=True, verbose_name='Pereigų pabaiga')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atnaujinta')),
            ],
            options={
                'verbose_name': 'Darbo patirties įrašas',
                'verbose_name_plural': 'Darbo patirties įrašai',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='europarliamentcandidate',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Gimimo data'),
        ),
        migrations.AddField(
            model_name='europarliamentcandidate',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100, verbose_name='Gimimo vieta'),
        ),
        migrations.AddField(
            model_name='europarliamentcandidate',
            name='hobbies',
            field=models.CharField(blank=True, max_length=500, verbose_name='Pomėgiai'),
        ),
        migrations.AddField(
            model_name='europarliamentcandidate',
            name='languages',
            field=models.CharField(blank=True, max_length=300, verbose_name='Užsienio kalbos'),
        ),
        migrations.AddField(
            model_name='presidentcandidate',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Gimimo data'),
        ),
        migrations.AddField(
            model_name='presidentcandidate',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100, verbose_name='Gimimo vieta'),
        ),
        migrations.AddField(
            model_name='presidentcandidate',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Kandidato el. paštas'),
        ),
        migrations.AddField(
            model_name='presidentcandidate',
            name='hobbies',
            field=models.CharField(blank=True, max_length=500, verbose_name='Pomėgiai'),
        ),
        migrations.AddField(
            model_name='presidentcandidate',
            name='languages',
            field=models.CharField(blank=True, max_length=300, verbose_name='Užsienio kalbos'),
        ),
        migrations.AlterField(
            model_name='presidentcandidate',
            name='party',
            field=models.CharField(blank=True, help_text='Jeigu kandidatas - be partijos, nurodykite, kad savarankiškas', max_length=280, verbose_name='Partija'),
        ),
        migrations.AddField(
            model_name='presidentcandidateworkexperience',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='elections.PresidentCandidate'),
        ),
        migrations.AddField(
            model_name='presidentcandidatepoliticalexperience',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='political_experience', to='elections.PresidentCandidate'),
        ),
        migrations.AddField(
            model_name='europarliamentcandidateworkexperience',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='elections.EuroParliamentCandidate'),
        ),
        migrations.AddField(
            model_name='europarliamentcandidatepoliticalexperience',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='political_experience', to='elections.EuroParliamentCandidate'),
        ),
        migrations.AddField(
            model_name='europarliamentcandidatebiography',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biographies', to='elections.EuroParliamentCandidate'),
        ),
    ]
