# Generated by Django 2.1.7 on 2019-05-11 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0049_auto_20190510_0736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='europarliamentcandidatepoliticalexperience',
            options={'ordering': ['created_at'], 'verbose_name': 'Politinės patirties įrašas', 'verbose_name_plural': 'Politinės patirties įrašai'},
        ),
        migrations.AlterModelOptions(
            name='presidentcandidatepoliticalexperience',
            options={'ordering': ['created_at'], 'verbose_name': 'Politinės patirties įrašas', 'verbose_name_plural': 'Politinės patirties įrašai'},
        ),
    ]
