# Generated by Django 2.1.7 on 2019-05-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0051_europarliamentcandidateconviction_europarliamentcandidateeducation'),
    ]

    operations = [
        migrations.AddField(
            model_name='europarliamentcandidateconviction',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nuosprendžio šalis'),
        ),
    ]
