# Generated by Django 2.1 on 2018-08-18 10:14

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('photo', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=False, quality=90, size=[256, 256], upload_to=web.models.OrganizationMember._organization_member_photo_file)),
                ('role', models.CharField(max_length=256)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Organization members',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMemberGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Organization member groups',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='web.OrganizationMemberGroup'),
        ),
    ]
