# Generated by Django 2.1 on 2018-08-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_emailsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('logo', models.ImageField(upload_to='')),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Organization partners',
                'ordering': ['order'],
            },
        ),
    ]
