# Generated by Django 2.1 on 2018-08-24 09:25

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_organizationmember_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationpartner',
            name='logo',
            field=models.ImageField(upload_to=web.models.OrganizationPartner._organization_partner_logo_file),
        ),
    ]
