# Generated by Django 2.1 on 2018-09-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20180824_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
