# Generated by Django 2.1.1 on 2018-10-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_organizationmember_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsubscription',
            name='user_country',
            field=models.TextField(blank=True, null=True),
        ),
    ]
