# Generated by Django 2.1.1 on 2018-10-02 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_emailsubscription_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmember',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
