# Generated by Django 2.1.1 on 2018-10-10 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_politicianinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicianinfo',
            name='seimas_politician',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='politician_info', to='seimas.Politician'),
        ),
    ]
