# Generated by Django 2.1.1 on 2018-10-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_unaccent_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsubscription',
            name='user_country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
