# Generated by Django 2.1.1 on 2018-11-05 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20181011_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='politicianinfo',
            options={'ordering': ['-created_at', 'name'], 'verbose_name': 'Politiko informacija', 'verbose_name_plural': 'Politikų informacija'},
        ),
        migrations.AlterField(
            model_name='politicianinfo',
            name='name',
            field=models.CharField(db_index=True, max_length=256, verbose_name='Politiko vardas'),
        ),
        migrations.AlterField(
            model_name='politicianinfo',
            name='seimas_politician',
            field=models.OneToOneField(blank=True, help_text='Sujungia seimo narį su politiku', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='politician_info', to='seimas.Politician', verbose_name='Seimo politiko profilis'),
        ),
        migrations.AlterField(
            model_name='politicianinfo',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Nustatytas vartotojas galės atsakinėti į klausimus skirtus politikui', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='politician_info', to=settings.AUTH_USER_MODEL, verbose_name='Vartotojas'),
        ),
    ]
