# Generated by Django 2.1.1 on 2018-11-13 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20181105_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailsubscription',
            options={'ordering': ['-created_at'], 'verbose_name': 'El. Pašto prenumerata', 'verbose_name_plural': 'El. Pašto prenumeratos'},
        ),
        migrations.AlterModelOptions(
            name='organizationmember',
            options={'ordering': ['order'], 'verbose_name': 'Organizacijos narys', 'verbose_name_plural': 'Organizacijos nariai'},
        ),
        migrations.AlterModelOptions(
            name='organizationmembergroup',
            options={'ordering': ['order'], 'verbose_name': 'Organizacijos narių komanda', 'verbose_name_plural': 'Organizacijos narių komandos'},
        ),
        migrations.AlterModelOptions(
            name='organizationpartner',
            options={'ordering': ['order'], 'verbose_name': 'Organizacijos partneris', 'verbose_name_plural': 'Organizacijos partneriai'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Registruotas vartotojas', 'verbose_name_plural': 'Registruoti vartotojai'},
        ),
        migrations.AlterField(
            model_name='emailsubscription',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='El. paštas'),
        ),
        migrations.AlterField(
            model_name='emailsubscription',
            name='user_country',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Šalis'),
        ),
        migrations.AlterField(
            model_name='emailsubscription',
            name='user_ip',
            field=models.GenericIPAddressField(verbose_name='IP adresas'),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='El. pašto adresas'),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Vardas'),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=False, quality=90, size=[256, 256], upload_to=web.models.OrganizationMember._organization_member_photo_file, verbose_name='Nuotrauka'),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='role',
            field=models.CharField(max_length=256, verbose_name='Nario rolė'),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Nustatyti šį laukelį, kad žmogus galėtų prisijungti prie admino', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_member', to=settings.AUTH_USER_MODEL, verbose_name='Registruotas vartotojas'),
        ),
        migrations.AlterField(
            model_name='organizationmembergroup',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Komandos pavadinimas'),
        ),
        migrations.AlterField(
            model_name='organizationpartner',
            name='logo',
            field=models.ImageField(upload_to=web.models.OrganizationPartner._organization_partner_logo_file, verbose_name='Logotipas'),
        ),
        migrations.AlterField(
            model_name='organizationpartner',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Pavadinimas'),
        ),
        migrations.AlterField(
            model_name='organizationpartner',
            name='url',
            field=models.URLField(verbose_name='Nuoroda į organizacijos puslapį'),
        ),
    ]
