# Generated by Django 2.1.1 on 2018-11-13 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20181113_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailsubscription',
            options={'ordering': ['-created_at'], 'verbose_name': 'El. pašto prenumerata', 'verbose_name_plural': 'El. pašto prenumeratos'},
        ),
    ]
