# Generated by Django 2.1.1 on 2018-12-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20181113_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, verbose_name='Savivaldybės pavadinimas')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Savivaldybė',
                'verbose_name_plural': 'Savivaldybės',
                'ordering': ['slug'],
            },
        ),
    ]
