# Generated by Django 2.1.1 on 2018-12-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_organizationmember_municipalities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmember',
            name='municipalities',
            field=models.ManyToManyField(blank=True, related_name='organization_members', to='web.Municipality', verbose_name='Savivaldybės'),
        ),
    ]
