# Generated by Django 2.1.1 on 2018-12-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20181202_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmember',
            name='municipalities',
            field=models.ManyToManyField(blank=True, help_text='Nurodomos savivaldybės, kurioms priklauso organizacijos narys', related_name='organization_members', to='web.Municipality', verbose_name='Savivaldybės'),
        ),
    ]
