# Generated by Django 2.1.1 on 2018-12-07 17:13

from django.db import migrations
import django_resized.forms
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_auto_20181203_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=False, null=True, quality=90, size=[256, 256], upload_to=web.models.User._user_photo_file, verbose_name='Nuotrauka'),
        ),
    ]
