# Generated by Django 2.1.1 on 2018-12-10 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_auto_20181207_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicianinfo',
            name='authenticated_users',
            field=models.ManyToManyField(blank=True, help_text='Nustatyti vartotojas galės atsakinėti į klausimus skirtus politikui', related_name='politician_infos', to=settings.AUTH_USER_MODEL, verbose_name='Vartotojai'),
        ),
        migrations.AddField(
            model_name='politicianinfo',
            name='registration_secret_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='politicianinfo',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vartotojas'),
        ),
    ]
