# Generated by Django 2.1.1 on 2018-12-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_auto_20181210_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_confirmation_letter_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
