# Generated by Django 2.1.1 on 2018-12-13 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_user_last_confirmation_letter_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_confirmation_letter_sent',
        ),
    ]
