# Generated by Django 2.1.5 on 2019-01-15 10:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_auto_20190103_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politicianinfo',
            name='user',
        ),
        migrations.AlterField(
            model_name='politicianinfo',
            name='authenticated_users',
            field=models.ManyToManyField(blank=True, help_text='Nustatyti vartotojai galės atsakinėti į klausimus skirtus politikui', related_name='politician_infos', to=settings.AUTH_USER_MODEL, verbose_name='Vartotojai'),
        ),
    ]
