# Generated by Django 2.1.5 on 2019-02-01 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0020_auto_20190129_1916'),
        ('web', '0033_politicianinfo_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicianinfo',
            name='mayor_candidate',
            field=models.OneToOneField(blank=True, help_text='Sujungia kandidatą į merus su politiku', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='politician_info', to='elections.MayorCandidate', verbose_name='Kandidatas į merus'),
        ),
    ]
