# Generated by Django 2.1.5 on 2019-02-01 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_politicianinfo_mayor_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicianinfo',
            name='mayor_candidate',
            field=models.OneToOneField(blank=True, help_text='Sujungia kandidatą į merus su politiku', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='politician_info', to='elections.MayorCandidate', verbose_name='Kandidatas į merus'),
        ),
    ]
