# Generated by Django 2.1.5 on 2019-02-18 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0033_auto_20190212_2339'),
        ('web', '0035_auto_20190201_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticianPromise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promise', models.TextField(verbose_name='Politiko pažadas')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promises', to='elections.Debates', verbose_name='Debatai')),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promises', to='web.PoliticianInfo', verbose_name='Politikas')),
            ],
            options={
                'verbose_name': 'Politiko pažadas',
                'verbose_name_plural': 'Politikų pažadai',
                'ordering': ['order'],
                'default_related_name': 'promises',
            },
        ),
    ]
