# Generated by Django 2.1.7 on 2019-04-11 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0045_auto_20190331_2117'),
        ('web', '0036_politicianpromise'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicianinfo',
            name='president_candidate',
            field=models.OneToOneField(blank=True, help_text='Sujungti kandidatą į LR Prezidento postą su politiku', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='politician_info', to='elections.PresidentCandidate', verbose_name='Kandidatas į LR Prezidento postą'),
        ),
    ]
