# Generated by Django 2.1.7 on 2019-05-10 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0049_auto_20190510_0736'),
        ('web', '0037_politicianinfo_president_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicianinfo',
            name='mep_candidate',
            field=models.OneToOneField(blank=True, help_text='Sujungti kandidatą į Europos Parlamentą su politiku', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='politician_info', to='elections.EuroParliamentCandidate', verbose_name='Kandidatas į Europos Parlamentą'),
        ),
    ]
