# Generated by Django 2.1.8 on 2019-05-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0037_politicianinfo_president_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicianinfo',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
