# Generated by Django 2.1.7 on 2019-05-11 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_politicianinfo_email'),
        ('web', '0038_politicianinfo_mep_candidate'),
    ]

    operations = [
    ]
