# Generated by Django 2.1.7 on 2019-05-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_merge_20190511_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicianinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='politiko el. paštas'),
        ),
    ]
