# Generated by Django 2.2.9 on 2019-12-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0040_auto_20190511_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_politician',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
