# Generated by Django 2.2.14 on 2020-08-07 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0054_seimascandidate'),
        ('web', '0041_user_is_politician'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicianinfo',
            name='seimas_candidate',
            field=models.OneToOneField(blank=True, help_text='Sujungia kandidatą į seimą su politiku', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='politician_info', to='elections.SeimasCandidate', verbose_name='Kandidatas į seimą'),
        ),
    ]
