# Generated by Django 2.2.9 on 2019-12-30 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politicians',
            name='slug',
        ),
    ]
