# Generated by Django 2.2.9 on 2019-12-30 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0002_remove_politicians_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politicians',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='politicians',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='promiseaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='promiseaction',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='promises',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='promises',
            name='updated_by',
        ),
    ]
