# Generated by Django 2.2.9 on 2020-01-04 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0004_auto_20191230_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promiseaction',
            name='promise_id',
        ),
        migrations.AddField(
            model_name='promiseaction',
            name='politician',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='politicians.Politicians'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promiseaction',
            name='promise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='politicians.Promises'),
            preserve_default=False,
        ),
    ]
