# Generated by Django 2.2.9 on 2020-01-04 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0005_auto_20200104_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promiseaction',
            name='politician',
        ),
    ]
