# Generated by Django 2.2.9 on 2020-01-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0007_auto_20200104_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='promises',
            name='total_score',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
