# Generated by Django 2.2.9 on 2020-01-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0008_promises_total_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promises',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nepradėtas'), (2, 'Procese'), (3, 'Užbaigtas')], null=True),
        ),
        migrations.AlterField(
            model_name='promises',
            name='total_score',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
