# Generated by Django 2.2.9 on 2020-01-05 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('politicians', '0009_auto_20200105_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('pol', 'Politinė patirtis'), ('work', 'Darbinė patirtis')], max_length=4, null=True, verbose_name='Patirties tipas')),
                ('pol_position', models.CharField(choices=[('mp', 'Seimo narys(-ė)'), ('mep', 'EP narys(-ė)'), ('pm', 'Premjeras(-ė)'), ('min', 'Ministras(-ė)'), ('my', 'Meras(-ė)'), ('mmu', 'Savivaldybės tarybos narys(-ė)'), ('ot', 'Kita')], max_length=4, verbose_name='Politinės preigos')),
                ('other_position', models.CharField(blank=True, help_text='Pildyti, kai yra nustatyta darbinės patirties tipas', max_length=300, null=True, verbose_name='Kitos pareigos')),
                ('institution', models.CharField(blank=True, max_length=300, null=True, verbose_name='Institucija/Įmonė')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Termino pradžia')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Termino pabaiga')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='politicians',
            name='is_mp',
        ),
        migrations.RemoveField(
            model_name='politicians',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='promises',
            name='target_deadline',
        ),
        migrations.AddField(
            model_name='politicians',
            name='asm_id',
            field=models.IntegerField(default='001', help_text='Asmens id is used internally in seimas web', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='politicians',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='politicians',
            name='user',
            field=models.OneToOneField(default='2', limit_choices_to={'is_politician': True}, on_delete=django.db.models.deletion.CASCADE, related_name='politicians', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promises',
            name='cancellation_reason_text',
            field=models.TextField(blank=True, null=True, verbose_name='Pažado neįgyvendinimo priežastis'),
        ),
        migrations.AddField(
            model_name='promises',
            name='commenst',
            field=models.TextField(blank=True, null=True, verbose_name='Komentarai'),
        ),
        migrations.AddField(
            model_name='promises',
            name='end_target_value',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Galutinis tikslo rezultatas'),
        ),
        migrations.AddField(
            model_name='promises',
            name='experts_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Eksperto komentaras'),
        ),
        migrations.AddField(
            model_name='promises',
            name='target_initial_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Pradinė tikslo įgyvendinimo data'),
        ),
        migrations.AddField(
            model_name='promises',
            name='target_new_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Nauja tikslo įgyvendinimo data'),
        ),
        migrations.AlterField(
            model_name='promiseaction',
            name='action_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Išsiųstas laiškas'), (2, 'Gautas laiškas'), (3, 'Tipas 3')], null=True),
        ),
        migrations.AlterField(
            model_name='promises',
            name='is_measurable',
            field=models.BooleanField(default=False, verbose_name='Ar pamatuojamas?'),
        ),
        migrations.AlterField(
            model_name='promises',
            name='promise_text',
            field=models.TextField(verbose_name='Pažadas'),
        ),
        migrations.AlterField(
            model_name='promises',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nepradėtas'), (2, 'Procese'), (3, 'Užbaigtas')], null=True, verbose_name='Būsena'),
        ),
        migrations.AlterField(
            model_name='promises',
            name='target',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Pažado tikslas'),
        ),
        migrations.AlterField(
            model_name='promises',
            name='total_score',
            field=models.IntegerField(default=0, editable=False, verbose_name='Bendradarbiavimo balas'),
        ),
        migrations.AlterField(
            model_name='promises',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Pažado įrašo nuoroda'),
        ),
        migrations.AddField(
            model_name='politicians',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='politicians', to='politicians.Experience'),
        ),
    ]
