# Generated by Django 2.2.9 on 2020-01-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0010_auto_20200105_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicians',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='politicians',
            name='first_name',
            field=models.CharField(default='Aloizas', max_length=50, verbose_name='Vardas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='politicians',
            name='last_name',
            field=models.CharField(default='Sakalas', max_length=150, verbose_name='Pavardė'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='politicians',
            name='personal_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politicians',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='politicians',
            name='slug',
            field=models.SlugField(default='aloizas-sakals', unique=True),
            preserve_default=False,
        ),
    ]
