# Generated by Django 2.2.9 on 2020-01-05 04:47

from django.db import migrations, models
import politicians.models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0011_auto_20200105_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='promiseaction',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=politicians.models.PromiseAction._monitoring_attachments, verbose_name='Prisegtukas'),
        ),
    ]
